version: 0.2

phases:

  build:
    commands:
      - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
      - git branch -a
      - echo $CODEBUILD_GIT_BRANCH
      - echo ${CODEBUILD_GIT_BRANCH}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - echo "${CODEBUILD_WEBHOOK_TRIGGER}"
      - |
        if expr "abc" == "abc"; then
        #if [ "abc" == "ProdEnv" ]; then
        echo "this is dev env"
        fi
