version: 0.2

phases:

  build:
    commands:
      - sh abc.sh
      #- read -p "Enter your name : " name
      #- echo "Hi, $name. Let us be friends!"
      - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
      - git branch -a
      - echo $CODEBUILD_GIT_BRANCH
      - echo ${CODEBUILD_GIT_BRANCH}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - echo "${CODEBUILD_WEBHOOK_TRIGGER}"
      - if expr "abc" == "abc"; then 
          try:
            echo "abcd"
          except:
            continue
      - |
        if expr "$code_source_branch" == "develop"; then
          echo "this is dev env"
          if expr "$qaautomationenv" == "devEnv"; then
              echo "Executing test on $qaautomationenv"
              # testing
              mvn clean test -DargLine=-Denv=${qaautomationenv} -Dsurefire.suiteXmlFiles=testNGExecution/sandbox.xml
              # testing
          fi
        fi
      - |
       if expr "abc" == "abc"; then
          # testing
          echo "this is dev env"
          if expr "xyz" == "xyz"; then
              mvn --help
          fi
       fi
