version: 0.2

phases:

  build:
    commands:
      - echo $CODEBUILD_GIT_BRANCH
      - |
        if expr "abc" == "abc"; then
        #if [ "abc" == "ProdEnv" ]; then
        echo "this is dev env"
        fi
